/*Problem Statement:
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

import java.util.ArrayList;

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        ArrayList<Character> sList=new ArrayList<Character>();
        for(int i=0;i<s.length();i++)
        {
            sList.add(s.charAt(i));
        }
        for(int i=0;i<t.length();i++)
        {
            if(!sList.contains(t.charAt(i)))
                return t.charAt(i);
            else
                sList.remove(sList.indexOf(t.charAt(i)));
        }
        return ' ';
    }

    public static void main(String[] args) {
        FindTheDifference ftd=new FindTheDifference();
        String str1="aA";
        String str2="a";
        char result=ftd.findTheDifference(str1,str2);
        System.out.println(result);
    }
}
